# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d257c3c8284f7ebb7af86736f2a7bdc282b537f047ef5598b9e888f0ced6affb61ff65726f7d565f2e862eb7228a26fe70c07f541e7657c8aa12482762fd3ec0

test:
  secret_key_base: a54f94bc51e671e312c5f229a1cf2d01f940943270af571b390c62fcf3d1f7c3471037b830d536ad6f27c38ac11da154a0f78dc1acd6c28552b45024fc952cf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
